pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/Dolev-Tz/Home-assignment.git', branch: 'main'
            }
        }
        stage('Setup Kubernetes Context') {
            steps {
                bat 'kubectl config current-context'
            }
        }
        stage('Install KEDA') {
            steps {
                bat '''
                helm repo add kedacore https://kedacore.github.io/charts
                helm repo update
                helm install keda kedacore/keda --namespace keda --create-namespace || true
                '''
            }
        }
        stage('Deploy Applications') {
            steps {
                bat '''
                kubectl create namespace my-app || true
                kubectl apply -f deploy_to_k8s/flask-deployment.yaml
                kubectl apply -f deploy_to_k8s/flask-service.yaml
                kubectl apply -f deploy_to_k8s/nginx-deployment.yaml
                kubectl apply -f deploy_to_k8s/nginx-service.yaml
                '''
            }
        }
        stage('Configure KEDA Scaling') {
            steps {
                bat '''
                kubectl apply -f flask-scaledobject.yaml
                '''
            }
        }
    }
}
